"""
Mock data for the E-Transaction Approval Dashboard prototype.
All data is fictional and for demonstration purposes only.
"""


def get_approval_tier(amount: float) -> str:
    """Return required approval / release tier based on transaction amount."""
    if amount >= 1_000_000:
        return "Vice President + CFO"
    if amount >= 500_000:
        return "Vice President"
    if amount >= 250_000:
        return "Controller"
    return "Senior Accounting Manager / Assistant Controller"


_TIER_STATUS_MAP = {
    "Senior Accounting Manager / Assistant Controller": "Pending SAM Approval",
    "Controller":                                       "Pending Controller Approval",
    "Vice President":                                   "Pending VP Approval",
    "Vice President + CFO":                             "Pending CFO Approval",
}


def tier_to_status(tier: str) -> str:
    """Map an approval tier string to its corresponding pending-approval status."""
    return _TIER_STATUS_MAP.get(tier, "Pending SAM Approval")


def mask_account(number: str) -> str:
    """Mask account number, showing only last 4 digits."""
    if not number or len(number) < 4:
        return "••••"
    return "••••••••" + number[-4:]


def mask_routing(number: str) -> str:
    """Mask routing number, showing only last 4 digits."""
    if not number or len(number) < 4:
        return "•••••"
    return "•••••" + number[-4:]


# ─────────────────────────────────────────────────────────────
#  Mock Request Records
#  7 scenarios covering a range of types, amounts, and statuses
# ─────────────────────────────────────────────────────────────
MOCK_REQUESTS = [
    # ── 1. Standard ACH under $250K — Completed ──────────────────
    {
        "request_id":            "TXN-2026-001",
        "submitted_date":        "2026-06-30",
        "request_type":          "ACH",
        "property_dept":         "Sunset Ridge Apartments",
        "property_code":         "SRA-001",
        "prepared_by":           "Maria Johnson",
        "prepared_date":         "2026-06-29",
        "controller_approver":   "Sarah Williams",
        "treasury_service_date": "2026-06-30",
        "last_used_date":        "2026-05-30",
        "amount":                145_000.00,
        "currency":              "USD",
        "approval_tier":         "Senior Accounting Manager / Assistant Controller",
        "status":                "Completed",
        "urgent":                False,
        "urgency_reason":        "",
        "assigned_approver":     "Tom Barrett",
        "days_pending":          0,
        "payment_purpose":       "Monthly vendor payment – landscaping services",
        "over_1m":               False,
        # Originating bank
        "orig_bank_name":        "Wells Fargo",
        "orig_account_name":     "Sunset Ridge Operating",
        "orig_account_number":   "4521039812",
        "orig_routing_number":   "121000248",
        "orig_bank_contact":     "Alex Morrison – (555) 204-1100",
        "notes_orig":            "",
        # Receiving bank
        "recv_payee_name":       "GreenScape Landscaping LLC",
        "recv_bank_name":        "Chase Bank",
        "recv_account_name":     "GreenScape Operating",
        "recv_account_number":   "9938271045",
        "recv_routing_number":   "021000021",
        "recv_bank_address":     "1234 Commerce Blvd, Phoenix, AZ 85001",
        "recv_contact_name":     "Joe Martinez",
        "recv_contact_email":    "j.martinez@greenscape.example.com",
        "recv_contact_phone":    "(555) 872-4400",
        "notes_recv":            "",
        # Verification
        "verbal_confirmed":          True,
        "verbal_confirmed_with":     "Known Contact",
        "verbal_contact_name":       "Joe Martinez",
        "verbal_confirm_datetime":   "2026-06-29 10:15 AM",
        "avs_score_entered":         True,
        "wf_screenshot_attached":    True,
        "external_source":           True,
        "internal_doc_not_used":     True,
        # Documents
        "docs_checklist": {
            "treasury_template":  True,
            "amount_backup":      True,
            "auth_to_move":       True,
            "exec_approval":      False,
            "external_wire_ach":  True,
            "wf_avs_screenshot":  True,
            "final_pdf":          True,
            "controller_signed":  True,
            "confirmation_email": True,
        },
        # Timeline
        "timeline": [
            {"date": "2026-06-29", "event": "Submitted by Maria Johnson",              "actor": "Maria Johnson",  "status": "Submitted",                    "type": "submitted"},
            {"date": "2026-06-29", "event": "Routed for Controller Approval",          "actor": "System",         "status": "Pending Controller Approval",  "type": "routed"},
            {"date": "2026-06-29", "event": "Approved by Controller – Tom Barrett",   "actor": "Tom Barrett",    "status": "Pending Treasury Review",      "type": "approve"},
            {"date": "2026-06-30", "event": "Treasury Review Complete",                "actor": "Sarah Williams", "status": "Pending Release",              "type": "treasury_reviewed"},
            {"date": "2026-06-30", "event": "Released by Tom Barrett",                 "actor": "Tom Barrett",    "status": "Released",                     "type": "mark_released"},
            {"date": "2026-06-30", "event": "Marked Completed – confirmation saved",   "actor": "Maria Johnson",  "status": "Completed",                    "type": "mark_completed"},
        ],
        "comments": [
            {"author": "Tom Barrett", "date": "2026-06-29", "text": "Verified with GreenScape contact directly. All documentation complete. Approved."},
        ],
    },

    # ── 2. Wire $250K–$500K — Pending Controller Approval ────────
    {
        "request_id":            "TXN-2026-002",
        "submitted_date":        "2026-07-01",
        "request_type":          "Wire",
        "property_dept":         "Corporate HQ",
        "property_code":         "CORP-001",
        "prepared_by":           "David Chen",
        "prepared_date":         "2026-06-30",
        "controller_approver":   "Sarah Williams",
        "treasury_service_date": "2026-07-03",
        "last_used_date":        "2026-01-15",
        "amount":                375_000.00,
        "currency":              "USD",
        "approval_tier":         "Controller",
        "status":                "Pending Controller Approval",
        "urgent":                False,
        "urgency_reason":        "",
        "assigned_approver":     "Sarah Williams",
        "days_pending":          7,
        "payment_purpose":       "Capital improvement fund transfer – roof replacement project",
        "over_1m":               False,
        "orig_bank_name":        "Wells Fargo",
        "orig_account_name":     "Corporate Capital Account",
        "orig_account_number":   "7834920156",
        "orig_routing_number":   "121000248",
        "orig_bank_contact":     "",
        "notes_orig":            "",
        "recv_payee_name":       "Summit Construction Group",
        "recv_bank_name":        "Bank of America",
        "recv_account_name":     "Summit Construction Operating",
        "recv_account_number":   "5523819402",
        "recv_routing_number":   "026009593",
        "recv_bank_address":     "500 Industrial Pkwy, Denver, CO 80201",
        "recv_contact_name":     "Patricia Nguyen",
        "recv_contact_email":    "p.nguyen@summitconstruction.example.com",
        "recv_contact_phone":    "(555) 344-9900",
        "notes_recv":            "",
        "verbal_confirmed":          True,
        "verbal_confirmed_with":     "Known Contact",
        "verbal_contact_name":       "Patricia Nguyen",
        "verbal_confirm_datetime":   "2026-06-30 2:30 PM",
        "avs_score_entered":         True,
        "wf_screenshot_attached":    True,
        "external_source":           True,
        "internal_doc_not_used":     True,
        "docs_checklist": {
            "treasury_template":  True,
            "amount_backup":      True,
            "auth_to_move":       True,
            "exec_approval":      False,
            "external_wire_ach":  True,
            "wf_avs_screenshot":  True,
            "final_pdf":          True,
            "controller_signed":  False,
            "confirmation_email": False,
        },
        "timeline": [
            {"date": "2026-07-01", "event": "Submitted by David Chen",         "actor": "David Chen", "status": "Submitted",                   "type": "submitted"},
            {"date": "2026-07-01", "event": "Routed for Controller Approval",  "actor": "System",     "status": "Pending Controller Approval", "type": "routed"},
        ],
        "comments": [],
    },

    # ── 3. Wire > $500K — Pending VP Approval ────────────────────
    {
        "request_id":            "TXN-2026-003",
        "submitted_date":        "2026-07-02",
        "request_type":          "Wire",
        "property_dept":         "Northgate Commercial",
        "property_code":         "NGC-003",
        "prepared_by":           "Lisa Park",
        "prepared_date":         "2026-07-01",
        "controller_approver":   "Sarah Williams",
        "treasury_service_date": "2026-07-08",
        "last_used_date":        "",
        "amount":                625_000.00,
        "currency":              "USD",
        "approval_tier":         "Vice President",
        "status":                "Pending VP Approval",
        "urgent":                False,
        "urgency_reason":        "",
        "assigned_approver":     "James Foster",
        "days_pending":          5,
        "payment_purpose":       "Property acquisition deposit – Northgate expansion phase 2",
        "over_1m":               False,
        "orig_bank_name":        "Wells Fargo",
        "orig_account_name":     "Northgate Acquisitions",
        "orig_account_number":   "3321094857",
        "orig_routing_number":   "121000248",
        "orig_bank_contact":     "Dana Pruitt – (555) 300-7755",
        "notes_orig":            "",
        "recv_payee_name":       "Northgate Properties LLC (Escrow)",
        "recv_bank_name":        "First National Bank",
        "recv_account_name":     "Northgate Escrow Account",
        "recv_account_number":   "1102938457",
        "recv_routing_number":   "031201360",
        "recv_bank_address":     "900 Northgate Plaza, Atlanta, GA 30301",
        "recv_contact_name":     "Marcus Webb",
        "recv_contact_email":    "m.webb@northgateprop.example.com",
        "recv_contact_phone":    "(555) 661-2200",
        "notes_recv":            "",
        "verbal_confirmed":          True,
        "verbal_confirmed_with":     "Known Contact",
        "verbal_contact_name":       "Marcus Webb",
        "verbal_confirm_datetime":   "2026-07-01 11:00 AM",
        "avs_score_entered":         True,
        "wf_screenshot_attached":    True,
        "external_source":           True,
        "internal_doc_not_used":     True,
        "docs_checklist": {
            "treasury_template":  True,
            "amount_backup":      True,
            "auth_to_move":       True,
            "exec_approval":      False,
            "external_wire_ach":  True,
            "wf_avs_screenshot":  True,
            "final_pdf":          False,
            "controller_signed":  False,
            "confirmation_email": False,
        },
        "timeline": [
            {"date": "2026-07-02", "event": "Submitted by Lisa Park",                         "actor": "Lisa Park",      "status": "Submitted",                   "type": "submitted"},
            {"date": "2026-07-02", "event": "Routed for Controller Approval",                 "actor": "System",         "status": "Pending Controller Approval", "type": "routed"},
            {"date": "2026-07-03", "event": "Approved by Controller – Sarah Williams",       "actor": "Sarah Williams", "status": "Pending VP Approval",         "type": "approve"},
        ],
        "comments": [
            {"author": "Sarah Williams", "date": "2026-07-03", "text": "New banking instructions – verbal confirmation completed with Marcus Webb. Amount exceeds $500K. Escalating to VP per policy."},
        ],
    },

    # ── 4. Wire > $1M — Pending CFO Approval ─────────────────────
    {
        "request_id":            "TXN-2026-004",
        "submitted_date":        "2026-07-03",
        "request_type":          "Wire",
        "property_dept":         "Downtown Portfolio",
        "property_code":         "DTP-007",
        "prepared_by":           "Robert Kim",
        "prepared_date":         "2026-07-02",
        "controller_approver":   "Sarah Williams",
        "treasury_service_date": "2026-07-10",
        "last_used_date":        "",
        "amount":                2_150_000.00,
        "currency":              "USD",
        "approval_tier":         "Vice President + CFO",
        "status":                "Pending CFO Approval",
        "urgent":                False,
        "urgency_reason":        "",
        "assigned_approver":     "Linda Martinez",
        "days_pending":          4,
        "payment_purpose":       "Building purchase – final closing payment",
        "over_1m":               True,
        "orig_bank_name":        "Wells Fargo",
        "orig_account_name":     "Downtown Portfolio Acquisitions",
        "orig_account_number":   "8821349567",
        "orig_routing_number":   "121000248",
        "orig_bank_contact":     "Alex Morrison – (555) 204-1100",
        "notes_orig":            "",
        "recv_payee_name":       "Metro Realty Group (Closing Escrow)",
        "recv_bank_name":        "JP Morgan Chase",
        "recv_account_name":     "Metro Realty Closing Escrow",
        "recv_account_number":   "7765432109",
        "recv_routing_number":   "021000021",
        "recv_bank_address":     "1 Wall Street, New York, NY 10005",
        "recv_contact_name":     "Charles Okonkwo",
        "recv_contact_email":    "c.okonkwo@metrorealty.example.com",
        "recv_contact_phone":    "(555) 200-0088",
        "notes_recv":            "Final closing — escrow held at JPM.",
        "verbal_confirmed":          True,
        "verbal_confirmed_with":     "Known Contact",
        "verbal_contact_name":       "Charles Okonkwo",
        "verbal_confirm_datetime":   "2026-07-02 3:00 PM",
        "avs_score_entered":         True,
        "wf_screenshot_attached":    True,
        "external_source":           True,
        "internal_doc_not_used":     True,
        "docs_checklist": {
            "treasury_template":  True,
            "amount_backup":      True,
            "auth_to_move":       True,
            "exec_approval":      True,
            "external_wire_ach":  True,
            "wf_avs_screenshot":  True,
            "final_pdf":          False,
            "controller_signed":  False,
            "confirmation_email": False,
        },
        "timeline": [
            {"date": "2026-07-03", "event": "Submitted by Robert Kim",                     "actor": "Robert Kim",     "status": "Submitted",                   "type": "submitted"},
            {"date": "2026-07-03", "event": "Routed for Controller Approval",               "actor": "System",         "status": "Pending Controller Approval", "type": "routed"},
            {"date": "2026-07-04", "event": "Approved by Controller – Sarah Williams",     "actor": "Sarah Williams", "status": "Pending VP Approval",         "type": "approve"},
            {"date": "2026-07-05", "event": "Approved by VP – James Foster",               "actor": "James Foster",   "status": "Pending CFO Approval",        "type": "approve"},
        ],
        "comments": [
            {"author": "Sarah Williams", "date": "2026-07-04", "text": "Amount exceeds $1M. Executive approval attached. Routing to VP per policy."},
            {"author": "James Foster",   "date": "2026-07-05", "text": "Approved. Amount exceeds $1M. Routing to CFO for required verbal and written approval per policy."},
        ],
    },

    # ── 5. Urgent ACH — Submitted, Needs Quick Action ────────────
    {
        "request_id":            "TXN-2026-005",
        "submitted_date":        "2026-07-07",
        "request_type":          "ACH",
        "property_dept":         "Riverside Commons",
        "property_code":         "RVC-002",
        "prepared_by":           "Susan Lee",
        "prepared_date":         "2026-07-07",
        "controller_approver":   "Tom Barrett",
        "treasury_service_date": "2026-07-08",
        "last_used_date":        "2026-03-15",
        "amount":                89_500.00,
        "currency":              "USD",
        "approval_tier":         "Senior Accounting Manager / Assistant Controller",
        "status":                "Pending SAM Approval",
        "urgent":                True,
        "urgency_reason":        "Vendor contract deadline – payment required by EOD to avoid $5,000 late penalty.",
        "assigned_approver":     "Tom Barrett",
        "days_pending":          1,
        "payment_purpose":       "Emergency HVAC repair – Advanced Air Systems Inc.",
        "over_1m":               False,
        "orig_bank_name":        "Wells Fargo",
        "orig_account_name":     "Riverside Commons Operating",
        "orig_account_number":   "6612304891",
        "orig_routing_number":   "121000248",
        "orig_bank_contact":     "",
        "notes_orig":            "",
        "recv_payee_name":       "Advanced Air Systems Inc.",
        "recv_bank_name":        "Regions Bank",
        "recv_account_name":     "Advanced Air Systems",
        "recv_account_number":   "4402938175",
        "recv_routing_number":   "062000019",
        "recv_bank_address":     "2900 Service Blvd, Orlando, FL 32801",
        "recv_contact_name":     "Ray Dobbins",
        "recv_contact_email":    "r.dobbins@advancedair.example.com",
        "recv_contact_phone":    "(555) 500-1122",
        "notes_recv":            "",
        "verbal_confirmed":          True,
        "verbal_confirmed_with":     "Known Contact",
        "verbal_contact_name":       "Ray Dobbins",
        "verbal_confirm_datetime":   "2026-07-07 9:00 AM",
        "avs_score_entered":         False,
        "wf_screenshot_attached":    False,
        "external_source":           True,
        "internal_doc_not_used":     True,
        "docs_checklist": {
            "treasury_template":  True,
            "amount_backup":      True,
            "auth_to_move":       False,
            "exec_approval":      False,
            "external_wire_ach":  True,
            "wf_avs_screenshot":  False,
            "final_pdf":          False,
            "controller_signed":  False,
            "confirmation_email": False,
        },
        "timeline": [
            {"date": "2026-07-07", "event": "Submitted by Susan Lee (URGENT)",  "actor": "Susan Lee", "status": "Submitted",             "type": "submitted"},
            {"date": "2026-07-07", "event": "Routed for SAM Approval (URGENT)", "actor": "System",    "status": "Pending SAM Approval", "type": "routed"},
        ],
        "comments": [
            {"author": "Susan Lee", "date": "2026-07-07", "text": "URGENT: HVAC compressor failed at Riverside Commons. Vendor requires payment by 5 PM today to begin repairs. AVS screenshot and authorization to move funds still pending – will follow up immediately."},
        ],
    },

    # ── 6. Intra Bank Transfer — Needs More Information ───────────
    {
        "request_id":            "TXN-2026-006",
        "submitted_date":        "2026-07-04",
        "request_type":          "Intra Bank Transfer",
        "property_dept":         "Westfield Portfolio",
        "property_code":         "WFP-004",
        "prepared_by":           "Kevin Thompson",
        "prepared_date":         "2026-07-04",
        "controller_approver":   "Sarah Williams",
        "treasury_service_date": "2026-07-07",
        "last_used_date":        "2026-04-05",
        "amount":                210_000.00,
        "currency":              "USD",
        "approval_tier":         "Senior Accounting Manager / Assistant Controller",
        "status":                "Needs More Information",
        "urgent":                False,
        "urgency_reason":        "",
        "assigned_approver":     "Sarah Williams",
        "days_pending":          3,
        "payment_purpose":       "Intercompany balance transfer – Q2 true-up",
        "over_1m":               False,
        "orig_bank_name":        "Wells Fargo",
        "orig_account_name":     "Westfield Operating",
        "orig_account_number":   "9934820177",
        "orig_routing_number":   "121000248",
        "orig_bank_contact":     "",
        "notes_orig":            "",
        "recv_payee_name":       "Westfield Capital Reserve",
        "recv_bank_name":        "Wells Fargo",
        "recv_account_name":     "Westfield Capital Reserve",
        "recv_account_number":   "9934820200",
        "recv_routing_number":   "121000248",
        "recv_bank_address":     "420 Montgomery St, San Francisco, CA 94104",
        "recv_contact_name":     "",
        "recv_contact_email":    "",
        "recv_contact_phone":    "",
        "notes_recv":            "Internal transfer between Westfield accounts.",
        "verbal_confirmed":          False,
        "verbal_confirmed_with":     "",
        "verbal_contact_name":       "",
        "verbal_confirm_datetime":   "",
        "avs_score_entered":         True,
        "wf_screenshot_attached":    True,
        "external_source":           False,
        "internal_doc_not_used":     False,
        "docs_checklist": {
            "treasury_template":  True,
            "amount_backup":      False,
            "auth_to_move":       False,
            "exec_approval":      False,
            "external_wire_ach":  False,
            "wf_avs_screenshot":  True,
            "final_pdf":          False,
            "controller_signed":  False,
            "confirmation_email": False,
        },
        "timeline": [
            {"date": "2026-07-04", "event": "Submitted by Kevin Thompson",          "actor": "Kevin Thompson", "status": "Submitted",                   "type": "submitted"},
            {"date": "2026-07-04", "event": "Routed for Controller Approval",       "actor": "System",         "status": "Pending Controller Approval", "type": "routed"},
            {"date": "2026-07-05", "event": "Returned – More Information Required", "actor": "Sarah Williams", "status": "Needs More Information",      "type": "more_info"},
        ],
        "comments": [
            {"author": "Sarah Williams", "date": "2026-07-05", "text": "Please provide backup documentation for the Q2 true-up amount and authorization to move funds. Also note: this appears to use an internal document as the banking instruction source – please provide an external source per policy."},
        ],
    },

    # ── 7. EFT (Canada) — Released ───────────────────────────────
    {
        "request_id":            "TXN-2026-007",
        "submitted_date":        "2026-06-28",
        "request_type":          "EFT",
        "property_dept":         "Canadian Operations",
        "property_code":         "CAN-001",
        "prepared_by":           "Natalie Bouchard",
        "prepared_date":         "2026-06-27",
        "controller_approver":   "Tom Barrett",
        "treasury_service_date": "2026-06-30",
        "last_used_date":        "2026-03-31",
        "amount":                95_000.00,
        "currency":              "CAD",
        "approval_tier":         "Senior Accounting Manager / Assistant Controller",
        "status":                "Released",
        "urgent":                False,
        "urgency_reason":        "",
        "assigned_approver":     "Tom Barrett",
        "days_pending":          0,
        "payment_purpose":       "Property management fee – Q2 2026",
        "over_1m":               False,
        "orig_bank_name":        "RBC Royal Bank",
        "orig_account_name":     "Canadian Operations CAD",
        "orig_account_number":   "5521083944",
        "orig_routing_number":   "003",
        "orig_bank_contact":     "Mireille Tremblay – (514) 555-9900",
        "notes_orig":            "Canadian transit number used in place of routing number.",
        "recv_payee_name":       "Northland Property Management Inc.",
        "recv_bank_name":        "TD Canada Trust",
        "recv_account_name":     "Northland Management",
        "recv_account_number":   "8833920122",
        "recv_routing_number":   "004",
        "recv_bank_address":     "100 Wellington St W, Toronto, ON M5K 1J3",
        "recv_contact_name":     "Pierre Lavoie",
        "recv_contact_email":    "p.lavoie@northlandmgmt.example.com",
        "recv_contact_phone":    "(416) 555-7700",
        "notes_recv":            "",
        "verbal_confirmed":          True,
        "verbal_confirmed_with":     "Known Contact",
        "verbal_contact_name":       "Pierre Lavoie",
        "verbal_confirm_datetime":   "2026-06-27 1:00 PM",
        "avs_score_entered":         True,
        "wf_screenshot_attached":    True,
        "external_source":           True,
        "internal_doc_not_used":     True,
        "docs_checklist": {
            "treasury_template":  True,
            "amount_backup":      True,
            "auth_to_move":       True,
            "exec_approval":      False,
            "external_wire_ach":  True,
            "wf_avs_screenshot":  True,
            "final_pdf":          True,
            "controller_signed":  True,
            "confirmation_email": False,
        },
        "timeline": [
            {"date": "2026-06-28", "event": "Submitted by Natalie Bouchard",           "actor": "Natalie Bouchard", "status": "Submitted",                   "type": "submitted"},
            {"date": "2026-06-28", "event": "Routed for Controller Approval",           "actor": "System",           "status": "Pending Controller Approval", "type": "routed"},
            {"date": "2026-06-29", "event": "Approved by Controller – Tom Barrett",    "actor": "Tom Barrett",      "status": "Pending Treasury Review",     "type": "approve"},
            {"date": "2026-06-29", "event": "Treasury Review Complete",                 "actor": "Tom Barrett",      "status": "Pending Release",             "type": "treasury_reviewed"},
            {"date": "2026-06-30", "event": "Released by Tom Barrett",                  "actor": "Tom Barrett",      "status": "Released",                    "type": "mark_released"},
        ],
        "comments": [
            {"author": "Tom Barrett", "date": "2026-06-29", "text": "EFT confirmed with Pierre Lavoie. All documents in order. Canadian transit numbers used as routing identifiers."},
        ],
    },
]


def get_request_by_id(request_id: str):
    """Look up a mock request by ID."""
    return next((r for r in MOCK_REQUESTS if r["request_id"] == request_id), None)
